[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sp-midi = { path = "../../crates/sp-midi" }
sp-shared-memory = { path = "../../crates/sp-shared-memory" }
sp-shared-memory-macos = { path = "../../crates/sp-shared-memory-macos" }
sp-supervisor = { path = "../../crates/sp-supervisor" }

[lints]
workspace = true
